export const pricingPlans = [
  {
    name: "Basic",
    price: "$9",
    period: "month",
    description: "Perfect for individuals and small projects",
    features: [
      "Basic AI features",
      "5 projects per month",
      "Standard support",
      "Basic analytics",
      "Community access",
    ],
    cta: "Get Started",
    popular: false,
  },
  {
    name: "Pro",
    price: "$0",
    period: "month",
    description: "Ideal for growing businesses",
    features: [
      "Advanced AI features",
      "Unlimited projects",
      "Priority support",
      "Advanced analytics",
      "API access",
      "Custom integrations",
    ],
    cta: "Start Free Trial",
    popular: true,
  },
  {
    name: "Enterprise",
    price: "Custom",
    period: "contact",
    description: "For large organizations",
    features: [
      "Custom AI solutions",
      "Unlimited everything",
      "24/7 dedicated support",
      "Custom analytics",
      "SLA guarantee",
      "On-premise deployment",
      "Custom training",
    ],
    cta: "Contact Sales",
    popular: false,
  },
];
